<?php

/**
 * @file
 * Provides a habitat entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function zoopal_habitat_theme() {
  return [
    'zoopal_habitat' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for habitat templates.
 *
 * Default template: zoopal-habitat.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the habitat information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_zoopal_habitat(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
