zoopal_creature.settings:
  type: config_object
  label: 'ZooPal Creature Settings'
  mapping:
    revision_default:
      type: boolean
      label: 'Create new revisions by default'

field.value.zoopal_creature_timeline:
  type: mapping
  label: Default value
  mapping:
    date:
      type: string
      label: Date
    description:
      type: text
      label: Description
