<?php

/**
 * @file
 * Provides a creature entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function zoopal_creature_theme() {
  return [
    'zoopal_creature' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for creature templates.
 *
 * Default template: zoopal-creature.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the creature information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_zoopal_creature(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
